import 'dart:convert' as dart_convert;
import 'dart:io' as dart_io;
import 'dart:math' as dart_math;

import 'package:obfuscator/src/collector.dart';
import 'package:obfuscator/src/config.dart';
import 'package:obfuscator/src/mappings.dart';

/// Object utilised for generating resources required for obfuscation operations.
///
class Generator {
  /// Generates an instance of the [collector] data generator with provided [configuration].
  ///
  Generator({
    required Configuration configuration,
    required ObjectCollector collector,
  }) : _configuration = configuration,
       _collector = collector,
       _random = dart_math.Random(configuration.seed);

  /// Object defining the basic input options for the obfuscation service.
  ///
  final Configuration _configuration;

  /// Property holding the value of the main object collector.
  ///
  final ObjectCollector _collector;

  /// Collection of names generated by the service.
  ///
  /// This value is referenced in order to avoid duplicate name entries.
  ///
  final _generatedNames = <String>{};

  /// Contextual and built-in language keywords.
  ///
  /// This value is referenced in order to avoid disallowed name entries.
  ///
  final _reservedKeywords = const {
    'abstract',
    'as',
    'assert',
    'async',
    'await',
    'base',
    'break',
    'case',
    'catch',
    'class',
    'const',
    'continue',
    'covariant',
    'default',
    'deferred',
    'do',
    'dynamic',
    'else',
    'enum',
    'export',
    'extends',
    'extension',
    'external',
    'factory',
    'false',
    'final',
    'finally',
    'for',
    'function',
    'get',
    'hide',
    'if',
    'implements',
    'import',
    'in',
    'interface',
    'is',
    'late',
    'library',
    'mixin',
    'new',
    'null',
    'of',
    'on',
    'operator',
    'part',
    'required',
    'rethrow',
    'return',
    'sealed',
    'set',
    'show',
    'static',
    'super',
    'switch',
    'sync',
    'this',
    'throw',
    'true',
    'try',
    'type',
    'typedef',
    'var',
    'void',
    'when',
    'while',
    'with',
    'yield',
  };

  /// Minimum length of a generated name, excluding the privacy prefix.
  ///
  static const _minimumNameLength = 8;

  /// Random value generator.
  ///
  final dart_math.Random _random;

  /// Generates a unique random name for the [symbol].
  ///
  /// Class names start with an uppercase letter and field names with a lowercase one.
  /// Private names remain private. Names never collide with the identifiers used in the source code.
  ///
  String _generateName(ObfuscatedSymbol symbol) {
    const letters = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
    const characters = '${letters}0123456789';
    final isPrivate = symbol.name.startsWith('_');
    final baseLength = dart_math.max(_minimumNameLength, symbol.name.length);
    late String value;
    do {
      final length = baseLength + _random.nextInt(baseLength + 1);
      final buffer = StringBuffer();
      for (var index = 0; index < length; index++) {
        final selection = index == 0 ? letters : characters;
        buffer.writeCharCode(selection.codeUnitAt(_random.nextInt(selection.length)));
      }
      value = buffer.toString();
      value = switch (symbol.kind) {
        ObfuscatedSymbolKind.classDeclaration => value[0].toUpperCase() + value.substring(1),
        ObfuscatedSymbolKind.field => value[0].toLowerCase() + value.substring(1),
      };
      if (isPrivate) value = '_$value';
    } while (_reservedKeywords.contains(value.toLowerCase()) ||
        _generatedNames.contains(value) ||
        _collector.usedIdentifiers.contains(value));
    _generatedNames.add(value);
    return value;
  }

  /// Replaces the copied file contents with the obfuscated identifiers and records the mappings.
  ///
  Future<void> processCopiedSourceDirectories() async {
    final mappings = <Mapping>[];
    final fileEdits = <String, List<({int offset, int length, String text, ObfuscatedSymbol symbol})>>{};

    for (final symbol in _collector.symbols) {
      final replacement = _generateName(symbol);
      for (final occurrence in symbol.occurrences) {
        fileEdits.putIfAbsent(occurrence.filePath, () => []).add(
          (offset: occurrence.offset, length: occurrence.length, text: replacement, symbol: symbol),
        );
      }
      final declaration = symbol.occurrences.firstWhere((occurrence) => occurrence.isDeclaration);
      mappings.add(
        Mapping(
          filePath: declaration.filePath,
          id: symbol.name,
          replacementId: replacement,
          parentId: symbol.parentName,
          offset: declaration.offset,
          referenceMappings: [
            for (final occurrence in symbol.occurrences)
              Mapping(
                filePath: occurrence.filePath,
                id: symbol.name,
                replacementId: replacement,
                parentId: symbol.parentName,
                offset: occurrence.offset,
                referenceMappings: null,
              ),
          ],
        ),
      );
    }

    for (final entry in fileEdits.entries) {
      final file = dart_io.File(entry.key);
      var contents = await file.readAsString();
      final edits = entry.value..sort((a, b) => b.offset.compareTo(a.offset));
      var previousOffset = contents.length + 1;
      for (final edit in edits) {
        // Edits are applied from the end of the file, so that the offsets remain valid.
        if (edit.offset + edit.length > previousOffset || (edit.offset == previousOffset && edit.length == 0)) {
          throw StateError('Overlapping replacements in ${file.path} at offset ${edit.offset}.');
        }
        if (edit.length > 0 && contents.substring(edit.offset, edit.offset + edit.length) != edit.symbol.name) {
          throw StateError(
            'Unexpected source contents in ${file.path} at offset ${edit.offset}, expected "${edit.symbol.name}".',
          );
        }
        contents = contents.replaceRange(edit.offset, edit.offset + edit.length, edit.text);
        previousOffset = edit.offset;
      }
      await file.writeAsString(contents);
      print('Obfuscated ${edits.length} identifier(s) in ${file.path}.');
    }

    // Record source code mappings.
    await _configuration.outputMappingsFile.writeAsString(
      dart_convert.jsonEncode(
        [for (final mapping in mappings) mapping.toJson()],
      ),
    );
  }
}
