import 'dart:convert' as dart_convert;
import 'dart:io' as dart_io;
import 'dart:math' as dart_math;

import 'package:analyzer/dart/analysis/analysis_context_collection.dart' as analyzer_context;
import 'package:analyzer/dart/analysis/results.dart' as analyzer_results;
import 'package:analyzer/dart/ast/ast.dart' as analyzer_ast;
import 'package:analyzer/dart/ast/token.dart' as analyzer_token;
import 'package:analyzer/dart/ast/visitor.dart' as analyzer_visitor;
import 'package:analyzer/dart/element/element.dart' as analyzer_element;
import 'package:obfuscator/src/collector.dart';
import 'package:obfuscator/src/config.dart';
import 'package:path/path.dart' as path;
import 'package:pub_semver/pub_semver.dart' as pub_semver;
import 'package:pubspec_parse/pubspec_parse.dart' as pubspec_parse;
import 'package:yaml_edit/yaml_edit.dart' as yaml_edit;

/// Resolved `lib` file of an obfuscated package, prepared for merging.
///
class _MergedSource {
  _MergedSource({
    required this.package,
    required this.filePath,
    required this.result,
  });

  final SourcePackage package;

  final String filePath;

  final analyzer_results.ResolvedUnitResult result;

  /// Text replacements applied to the file contents before merging.
  ///
  /// Edits at the same offset are applied by their `priority` (lower first), then in the order of addition.
  ///
  final edits = <({int offset, int end, String text, int priority, int order})>[];

  final _editKeys = <(int, int, String)>{};

  void addEdit(int offset, int end, String text, {int priority = 1}) {
    if (_editKeys.add((offset, end, text))) {
      edits.add((offset: offset, end: end, text: text, priority: priority, order: edits.length));
    }
  }
}

/// Third-party library exported by a merged library, with the combinators applied to it, in the order of application.
///
typedef _Export = ({analyzer_element.LibraryElement library, List<analyzer_element.NamespaceCombinator> combinators});

/// Import directive of the merged file.
///
class _MergedImport {
  _MergedImport({
    required this.source,
    required this.libraryKey,
    required this.prefix,
    required this.isDeferred,
    required String Function(String? prefix) render,
  }) : _render = render;

  /// The merged file which declared the import, or `null` for the imports generated by the merger.
  ///
  final _MergedSource? source;

  /// Identifier of the imported library.
  ///
  final String libraryKey;

  /// Import prefix, which may be renamed to avoid clashes between the merged files.
  ///
  String? prefix;

  /// Whether the library is loaded lazily.
  ///
  final bool isDeferred;

  final String Function(String? prefix) _render;

  /// Source code of the directive.
  ///
  String get text => _render(prefix);
}

/// Reference to a top-level declaration, which may require renaming or a prefix in the merged file.
///
class _TopLevelReference {
  _TopLevelReference({
    required this.source,
    required this.offset,
    required this.end,
    required this.element,
  });

  final _MergedSource source;

  final int offset;

  final int end;

  final analyzer_element.Element element;
}

/// Class used for merging all of the available source code directories into a single file.
///
class ProjectMerger {
  /// Class used for merging all of the available source code directories into a single file,
  /// according to the provided [configuration].
  ///
  ProjectMerger({
    required Configuration configuration,
    required ObjectCollector collector,
  }) : _configuration = configuration,
       _collector = collector;

  /// Object defining the basic input options for the obfuscation service.
  ///
  final Configuration _configuration;

  /// Property holding the value of the main object collector.
  ///
  final ObjectCollector _collector;

  /// Whether the [library] is one of the obfuscated libraries, merged into the output file.
  ///
  bool _isMergedLibrary(analyzer_element.LibraryElement? library) {
    if (library == null) return false;
    final uri = library.uri;
    if (uri.scheme == 'package') {
      return uri.pathSegments.isNotEmpty && _configuration.sourcePackages.contains(uri.pathSegments.first);
    }
    if (uri.scheme == 'file') {
      final filePath = uri.toFilePath();
      return _configuration.packages.any((package) => path.isWithin(path.join(package.copyDirectory.path, 'lib'), filePath));
    }
    return false;
  }

  /// Returns the top-level declaration an [element] reference resolves to, if any.
  ///
  static analyzer_element.Element? _topLevelElement(analyzer_element.Element? element) {
    if (element == null) return null;
    var base = element.baseElement;
    if (base is analyzer_element.ConstructorElement) return null;
    if (base is analyzer_element.PropertyAccessorElement) base = base.variable;
    if (base is analyzer_element.PrefixElement || base is analyzer_element.LibraryElement) return null;
    if (base.enclosingElement is! analyzer_element.LibraryElement) return null;
    final name = base.name;
    if (name == null || name.isEmpty || base.library == null) return null;
    return base;
  }

  /// Unique identifier of a top-level [element].
  ///
  static String _topLevelKey(analyzer_element.Element element) => '${element.library!.uri}#${element.name}';

  /// Resolves the `lib` files of the obfuscated packages.
  ///
  Future<List<_MergedSource>> _resolveSources(analyzer_context.AnalysisContextCollection collection) async {
    final sources = <_MergedSource>[];
    for (final package in _configuration.packages) {
      for (final filePath in ObjectCollector.listDartFiles(package)) {
        if (!ObjectCollector.isLibraryFile(package, filePath)) continue;
        final context = ObjectCollector.contextFor(collection, filePath);
        final result = await context.currentSession.getResolvedUnit(filePath);
        if (result is! analyzer_results.ResolvedUnitResult) {
          throw ConfigurationException('Unable to analyze "$filePath" for merging: ${result.runtimeType}.');
        }
        sources.add(_MergedSource(package: package, filePath: filePath, result: result));
      }
    }
    return sources;
  }

  /// Collects the directive removals, and the references to top-level declarations.
  ///
  List<_TopLevelReference> _prepareSources(
    List<_MergedSource> sources,
    List<_MergedImport> imports,
  ) {
    final references = <_TopLevelReference>[];
    for (final source in sources) {
      for (final directive in source.result.unit.directives) {
        if (directive is analyzer_ast.ImportDirective) {
          final importedLibrary = directive.libraryImport?.importedLibrary;
          final prefix = directive.prefix?.name;
          if (!_isMergedLibrary(importedLibrary)) {
            imports.add(
              _MergedImport(
                source: source,
                libraryKey: importedLibrary?.uri.toString() ?? directive.uri.toSource(),
                prefix: prefix,
                isDeferred: directive.deferredKeyword != null,
                render: (prefix) => [
                  'import ${directive.uri.toSource()}',
                  for (final configuration in directive.configurations) configuration.toSource(),
                  if (directive.deferredKeyword != null) 'deferred',
                  if (prefix != null) 'as $prefix',
                  for (final combinator in directive.combinators) combinator.toSource(),
                ].join(' '),
              ),
            );
            if (importedLibrary == null) {
              print('Warning: unresolved import "${directive.uri.stringValue}" in ${source.filePath}.');
            }
          } else {
            // Third-party libraries re-exported by the merged library are imported directly, with the same
            // prefix and combinators. Deferred loading is dropped, as the merged library is always loaded.
            for (final export in _externalExports(importedLibrary!)) {
              imports.add(
                _MergedImport(
                  source: source,
                  libraryKey: export.library.uri.toString(),
                  prefix: prefix,
                  isDeferred: false,
                  render: (prefix) => [
                    "import '${export.library.uri}'",
                    if (prefix != null) 'as $prefix',
                    for (final combinator in export.combinators) _combinatorSource(combinator),
                    for (final combinator in directive.combinators) combinator.toSource(),
                  ].join(' '),
                ),
              );
            }
          }
        }
        source.addEdit(directive.offset, _endOfTrailingComment(source.result.content, directive.end), '');
      }
      source.result.unit.accept(
        _MergeReferenceVisitor(
          merger: this,
          source: source,
          references: references,
        ),
      );
    }
    return references;
  }

  /// Import prefix tokens of the references to third-party libraries, which are kept in the merged file.
  ///
  final _prefixUsages = <({_MergedSource source, analyzer_token.Token token})>[];

  /// Source code of a [combinator].
  ///
  static String _combinatorSource(analyzer_element.NamespaceCombinator combinator) {
    return switch (combinator) {
      analyzer_element.ShowElementCombinator(:final shownNames) => 'show ${shownNames.join(', ')}',
      analyzer_element.HideElementCombinator(:final hiddenNames) => 'hide ${hiddenNames.join(', ')}',
    };
  }

  /// Whether the [name] is visible through all of the [combinators].
  ///
  static bool _isVisible(String name, List<analyzer_element.NamespaceCombinator> combinators) {
    return combinators.every(
      (combinator) => switch (combinator) {
        analyzer_element.ShowElementCombinator(:final shownNames) => shownNames.contains(name),
        analyzer_element.HideElementCombinator(:final hiddenNames) => !hiddenNames.contains(name),
      },
    );
  }

  /// Top-level declarations visible through the [export], mapped by their names.
  ///
  static Map<String, analyzer_element.Element> _exportedElements(_Export export) {
    return {
      for (final entry in export.library.exportNamespace.definedNames2.entries)
        if (_topLevelElement(entry.value) case final element?)
          if (_isVisible(entry.key.replaceAll('=', ''), export.combinators)) entry.key.replaceAll('=', ''): element,
    };
  }

  /// Third-party libraries exported by the merged libraries, mapped by the exporting library URIs.
  ///
  final _externalExportsCache = <Uri, List<_Export>>{};

  /// Third-party libraries exported by the merged [library], directly or through other merged libraries.
  ///
  /// Each export path is followed, so that the combinators of all of the paths are applied.
  ///
  List<_Export> _externalExports(analyzer_element.LibraryElement library) => _collectExternalExports(library, {}).exports;

  /// Collects the third-party exports of the [library], skipping the libraries [inProgress] (export cycles).
  ///
  /// The results are cached, unless an export cycle was skipped while collecting them.
  ///
  ({List<_Export> exports, bool isComplete}) _collectExternalExports(
    analyzer_element.LibraryElement library,
    Set<Uri> inProgress,
  ) {
    final cached = _externalExportsCache[library.uri];
    if (cached != null) return (exports: cached, isComplete: true);
    inProgress.add(library.uri);
    var isComplete = true;
    final exports = <String, _Export>{};
    void add(_Export export) {
      final key = [export.library.uri, for (final combinator in export.combinators) _combinatorSource(combinator)].join(' ');
      exports.putIfAbsent(key, () => export);
    }

    for (final fragment in library.fragments) {
      for (final export in fragment.libraryExports) {
        final exportedLibrary = export.exportedLibrary;
        if (exportedLibrary == null) continue;
        if (!_isMergedLibrary(exportedLibrary)) {
          add((library: exportedLibrary, combinators: export.combinators));
        } else if (inProgress.contains(exportedLibrary.uri)) {
          isComplete = false;
        } else {
          final nested = _collectExternalExports(exportedLibrary, inProgress);
          isComplete = isComplete && nested.isComplete;
          for (final nestedExport in nested.exports) {
            add((library: nestedExport.library, combinators: [...nestedExport.combinators, ...export.combinators]));
          }
        }
      }
    }
    inProgress.remove(library.uri);
    final result = exports.values.toList();
    if (isComplete) _externalExportsCache[library.uri] = result;
    return (exports: result, isComplete: isComplete);
  }

  /// Third-party libraries exported by the public (non-`src`) merged libraries, which remain exported
  /// by the merged file.
  ///
  /// Only the names which the public library actually exports from the third-party library are exported,
  /// e.g., not the ones shadowed by its own declarations. Names exported from different declarations by
  /// multiple libraries are exported only by the first one.
  ///
  List<String> _publicExports(List<_MergedSource> sources, Map<String, analyzer_element.Element> exportedNames) {
    final exports = <String>[];
    final visitedLibraries = <Uri>{};
    for (final source in sources) {
      final library = source.result.libraryElement;
      final libPath = path.join(source.package.copyDirectory.path, 'lib');
      if (path.isWithin(path.join(libPath, 'src'), source.filePath) || !visitedLibraries.add(library.uri)) continue;
      for (final export in _externalExports(library)) {
        final hiddenNames = <String>[];
        final exportedElements = _exportedElements(export);
        for (final entry in exportedElements.entries) {
          final exported = _topLevelElement(library.exportNamespace.get2(entry.key));
          if (exported == null || _topLevelKey(exported) != _topLevelKey(entry.value)) {
            hiddenNames.add(entry.key);
            continue;
          }
          final existing = exportedNames.putIfAbsent(entry.key, () => entry.value);
          if (_topLevelKey(existing) != _topLevelKey(entry.value)) {
            print('Warning: "${entry.key}" is exported by multiple libraries, only the first one is exported.');
            hiddenNames.add(entry.key);
          }
        }
        if (hiddenNames.length == exportedElements.length) continue;
        final text = [
          "export '${export.library.uri}'",
          for (final combinator in export.combinators) _combinatorSource(combinator),
          if (hiddenNames.isNotEmpty) 'hide ${hiddenNames.join(', ')}',
        ].join(' ');
        if (!exports.contains('$text;')) exports.add('$text;');
      }
    }
    return exports;
  }

  /// New names of the top-level declarations renamed to avoid clashes, mapped by their keys.
  ///
  final _topLevelRenames = <String, String>{};

  /// Unique identifier of an extension [element], including the unnamed ones.
  ///
  static String _extensionKey(analyzer_element.ExtensionElement element) {
    return '${element.library.uri}#${element.name ?? ''}@${element.firstFragment.offset}';
  }

  /// Names of the instance members declared by an extension [element].
  ///
  static Set<String> _extensionMemberNames(analyzer_element.ExtensionElement element) {
    return {
      for (final member in <analyzer_element.ExecutableElement>[...element.methods, ...element.getters, ...element.setters])
        if (!member.isStatic && member.name != null) member.name!,
    };
  }

  /// Makes the extension member invocations explicit where more extensions become visible once merged.
  ///
  /// An extension declared by another merged library, or imported by another merged file, may be more specific
  /// than the one an invocation originally resolved to, or make it ambiguous. Such invocations are rewritten to
  /// explicit extension overrides (e.g., `OnObject(value).describe()`), naming the unnamed extensions if needed.
  ///
  void _resolveExtensionClashes(List<_MergedSource> sources, Set<String> usedNames) {
    final visibleBySource = {
      for (final source in sources)
        source: {
          for (final extension in source.result.libraryFragment.accessibleExtensions) _extensionKey(extension): extension,
        },
    };
    final mergedScope = <String, analyzer_element.ExtensionElement>{
      for (final visible in visibleBySource.values) ...visible,
    };
    final declarations = <String, (_MergedSource, analyzer_ast.ExtensionDeclaration)>{
      for (final source in sources)
        for (final declaration in source.result.unit.declarations.whereType<analyzer_ast.ExtensionDeclaration>())
          if (declaration.declaredFragment?.element case final element?) _extensionKey(element): (source, declaration),
    };
    final overrideNames = <String, String?>{};

    String? overrideName(_MergedSource source, analyzer_element.ExtensionElement extension) {
      final key = _extensionKey(extension);
      if (!_isMergedLibrary(extension.library)) {
        // Third-party extensions can be named only if they are imported without a prefix.
        final name = extension.name;
        if (name == null) return null;
        final isImported = source.result.libraryFragment.libraryImports.any((import) {
          final imported = import.prefix == null ? import.namespace.get2(name) : null;
          return imported is analyzer_element.ExtensionElement && _extensionKey(imported) == key;
        });
        return isImported ? name : null;
      }
      return overrideNames.putIfAbsent(key, () {
        final name = extension.name;
        if (name != null) return _topLevelRenames[_topLevelKey(extension)] ?? name;
        final declaration = declarations[key];
        if (declaration == null) return null;
        var index = 0;
        var newName = '_MergedExtension$index';
        while (usedNames.contains(newName)) {
          newName = '_MergedExtension${++index}';
        }
        usedNames.add(newName);
        final keyword = declaration.$2.extensionKeyword;
        declaration.$1.addEdit(keyword.end, keyword.end, ' $newName');
        return newName;
      });
    }

    for (final source in sources) {
      final visible = visibleBySource[source]!;
      final memberNames = {
        for (final entry in mergedScope.entries)
          if (!visible.containsKey(entry.key)) ..._extensionMemberNames(entry.value),
      };
      if (memberNames.isEmpty) continue;
      source.result.unit.accept(
        _ExtensionOverrideVisitor(
          source: source,
          memberNames: memberNames,
          overrideName: (extension) => overrideName(source, extension),
        ),
      );
    }
  }

  /// Unique identifier of a private class or extension member an [element] reference resolves to,
  /// or `null` if the element isn't such a member.
  ///
  static String? _privateMemberKey(analyzer_element.Element? element) {
    var base = element?.baseElement;
    if (base is analyzer_element.FieldFormalParameterElement) base = base.field;
    if (base is analyzer_element.PropertyAccessorElement) base = base.variable;
    if (base is! analyzer_element.FieldElement && base is! analyzer_element.MethodElement) return null;
    final name = base!.name;
    if (name == null || !name.startsWith('_') || base.enclosingElement is! analyzer_element.InstanceElement) return null;
    return '${base.library!.uri}#$name';
  }

  /// Name tokens of the members declared by a class-like or extension [declaration].
  ///
  static Iterable<analyzer_token.Token> _memberNames(analyzer_ast.CompilationUnitMember declaration) sync* {
    final members = switch (declaration) {
      analyzer_ast.ClassDeclaration(:final members) ||
      analyzer_ast.MixinDeclaration(:final members) ||
      analyzer_ast.EnumDeclaration(:final members) ||
      analyzer_ast.ExtensionDeclaration(:final members) ||
      analyzer_ast.ExtensionTypeDeclaration(:final members) => members,
      _ => const <analyzer_ast.ClassMember>[],
    };
    if (declaration is analyzer_ast.ExtensionTypeDeclaration) yield declaration.representation.fieldName;
    for (final member in members) {
      if (member is analyzer_ast.MethodDeclaration) yield member.name;
      if (member is analyzer_ast.FieldDeclaration) {
        for (final variable in member.fields.variables) {
          yield variable.name;
        }
      }
    }
  }

  /// Renames the private members declared under the same names by multiple merged libraries.
  ///
  /// Private members of different libraries are unrelated, but once the libraries are merged, they would
  /// override or conflict with one another (e.g., `Child._init` would start overriding `Base._init`).
  ///
  void _resolvePrivateMemberClashes(List<_MergedSource> sources, Set<String> usedNames) {
    final librariesByName = <String, Set<Uri>>{};
    for (final source in sources) {
      for (final declaration in source.result.unit.declarations) {
        for (final name in _memberNames(declaration)) {
          if (name.lexeme.startsWith('_')) {
            librariesByName.putIfAbsent(name.lexeme, () => {}).add(source.result.libraryElement.uri);
          }
        }
      }
    }
    final renames = <String, String>{};
    for (final entry in librariesByName.entries) {
      for (final library in entry.value.skip(1)) {
        var index = 1;
        var newName = '${entry.key}_$index';
        while (usedNames.contains(newName)) {
          newName = '${entry.key}_${++index}';
        }
        usedNames.add(newName);
        renames['$library#${entry.key}'] = newName;
        print('Renamed the private "${entry.key}" members of $library to "$newName" to avoid clashes between the merged libraries.');
      }
    }
    if (renames.isEmpty) return;
    for (final source in sources) {
      source.result.unit.accept(_PrivateMemberVisitor(source: source, renames: renames));
    }
  }

  /// Renames the import prefixes shared by merged files for different libraries.
  ///
  /// A prefix may be shared by multiple files only if it refers to the same libraries in all of them.
  ///
  void _resolvePrefixClashes(List<_MergedImport> imports, Set<String> usedNames) {
    final importsBySourcePrefix = <(_MergedSource, String), List<_MergedImport>>{};
    for (final import in imports) {
      final source = import.source, prefix = import.prefix;
      if (source == null || prefix == null) continue;
      importsBySourcePrefix.putIfAbsent((source, prefix), () => []).add(import);
    }
    // Sources grouped by the prefix name and by the libraries it refers to.
    final bindings = <String, Map<String, List<_MergedSource>>>{};
    for (final entry in importsBySourcePrefix.entries) {
      final binding = ([
        for (final import in entry.value) import.isDeferred ? 'deferred ${import.text}' : import.libraryKey,
      ]..sort()).toSet().join('\n');
      bindings.putIfAbsent(entry.key.$2, () => {}).putIfAbsent(binding, () => []).add(entry.key.$1);
    }
    for (final entry in bindings.entries) {
      final prefix = entry.key;
      final isDeferred = entry.value.keys.any((binding) => binding.startsWith('deferred '));
      final groups = entry.value.values.toList();
      // Deferred prefixes can't be shared with any other import, even of the same library.
      final renamedGroups = isDeferred
          ? groups
                .expand(
                  (group) => [
                    for (final source in group) [source],
                  ],
                )
                .skip(1)
          : groups.skip(1);
      for (final group in renamedGroups) {
        var index = 1;
        var newPrefix = '${prefix}_$index';
        while (usedNames.contains(newPrefix)) {
          newPrefix = '${prefix}_${++index}';
        }
        usedNames.add(newPrefix);
        for (final source in group) {
          for (final import in importsBySourcePrefix[(source, prefix)]!) {
            import.prefix = newPrefix;
          }
          for (final usage in _prefixUsages) {
            if (usage.source == source && usage.token.lexeme == prefix) {
              source.addEdit(usage.token.offset, usage.token.end, newPrefix);
            }
          }
        }
        print('Renamed the "$prefix" import prefix to "$newPrefix" to avoid a clash between the merged files.');
      }
    }
  }

  /// Returns the end of a comment following the [offset] on the same line, or the [offset] itself.
  ///
  static int _endOfTrailingComment(String contents, int offset) {
    final lineEnd = contents.indexOf('\n', offset);
    final rest = contents.substring(offset, lineEnd == -1 ? contents.length : lineEnd);
    return RegExp(r'^[ \t]*//').hasMatch(rest) ? offset + rest.trimRight().length : offset;
  }

  /// Finds the top-level names which would clash once the libraries are merged, and renames them.
  ///
  /// First-party top-level declarations are renamed if the same name is declared by multiple
  /// libraries, if the name refers to a different, third-party declaration in any of the libraries,
  /// or if the name is used as an import prefix.
  /// Third-party references with ambiguous names are prefixed with a dedicated import.
  ///
  void _resolveNameClashes(
    List<_MergedSource> sources,
    List<_TopLevelReference> references,
    List<_MergedImport> imports,
    Set<String> usedNames,
    Map<String, analyzer_element.Element> exportedNames,
  ) {
    final prefixes = {for (final import in imports) ?import.prefix};
    // First-party top-level declarations, in the order of declaration.
    final declarations = <String, analyzer_element.Element>{};
    for (final source in sources) {
      for (final declaration in source.result.unit.declarations) {
        for (final (element, _) in _declaredTopLevelElements(declaration)) {
          declarations.putIfAbsent(_topLevelKey(element), () => element);
        }
      }
    }
    final externalReferencesByName = <String, Map<String, List<_TopLevelReference>>>{};
    for (final reference in references) {
      if (_isMergedLibrary(reference.element.library)) continue;
      externalReferencesByName
          .putIfAbsent(reference.element.name!, () => {})
          .putIfAbsent(_topLevelKey(reference.element), () => [])
          .add(reference);
    }

    final renames = _topLevelRenames;
    final declaredNames = <String>{};
    for (final entry in declarations.entries) {
      final name = entry.value.name!;
      final isExportedElsewhere = exportedNames.containsKey(name) && !_isMergedLibrary(exportedNames[name]!.library);
      if (declaredNames.add(name) && !externalReferencesByName.containsKey(name) && !prefixes.contains(name) && !isExportedElsewhere) {
        continue;
      }
      var index = 1;
      var newName = '${name}_$index';
      while (usedNames.contains(newName)) {
        newName = '${name}_${++index}';
      }
      usedNames.add(newName);
      renames[entry.key] = newName;
      print('Renamed the top-level declaration "$name" of ${entry.value.library!.uri} to "$newName" to avoid a name clash.');
    }

    for (final source in sources) {
      for (final declaration in source.result.unit.declarations) {
        for (final (element, token) in _declaredTopLevelElements(declaration)) {
          final newName = renames[_topLevelKey(element)];
          if (newName != null) source.addEdit(token.offset, token.end, newName);
        }
      }
    }
    for (final reference in references) {
      final newName = renames[_topLevelKey(reference.element)];
      if (newName != null) reference.source.addEdit(reference.offset, reference.end, newName);
    }

    // Third-party declarations provided under the [name] by the unprefixed imports of any of the merged files.
    // Once merged, all of them are visible to all of the files, regardless of the combinators of other files.
    Set<String> providers(String name) => {
      for (final source in sources)
        for (final import in source.result.libraryFragment.libraryImports)
          if (import.prefix == null)
            if (_topLevelElement(import.namespace.get2(name)) case final element?)
              if (!_isMergedLibrary(element.library)) _topLevelKey(element),
    };

    // Third-party names which are ambiguous in the merged file are accessed with dedicated import prefixes.
    var prefixIndex = 0;
    for (final entry in externalReferencesByName.entries) {
      if (entry.value.length < 2 && providers(entry.key).length < 2) continue;
      for (final elementReferences in entry.value.values) {
        final reference = elementReferences.first;
        final importUri = _findImportUri(reference.source, reference.element);
        if (importUri == null) {
          print('Warning: unable to disambiguate the "${entry.key}" name in the merged file.');
          continue;
        }
        String prefix;
        do {
          prefix = '_merged_import_${prefixIndex++}';
        } while (usedNames.contains(prefix));
        usedNames.add(prefix);
        imports.add(
          _MergedImport(
            source: null,
            libraryKey: importUri,
            prefix: prefix,
            isDeferred: false,
            render: (prefix) => "import '$importUri' as $prefix",
          ),
        );
        for (final elementReference in elementReferences) {
          elementReference.source.addEdit(elementReference.offset, elementReference.offset, '$prefix.');
        }
      }
    }
  }

  /// Returns the URI of an import through which the [element] is referenced by the [source].
  ///
  String? _findImportUri(_MergedSource source, analyzer_element.Element element) {
    final libraryFragment = source.result.libraryElement.firstFragment;
    for (final import in libraryFragment.libraryImports) {
      if (import.prefix != null) continue;
      final importedElement = _topLevelElement(import.namespace.get2(element.name!));
      if (importedElement == null || _topLevelKey(importedElement) != _topLevelKey(element)) continue;
      final importedLibrary = import.importedLibrary;
      if (importedLibrary == null) continue;
      if (!_isMergedLibrary(importedLibrary)) return importedLibrary.uri.toString();
      // The element is re-exported by a merged library, it's imported from the exporting third-party library.
      for (final export in _externalExports(importedLibrary)) {
        final exportedElement = _exportedElements(export)[element.name];
        if (exportedElement != null && _topLevelKey(exportedElement) == _topLevelKey(element)) {
          return export.library.uri.toString();
        }
      }
    }
    return null;
  }

  /// Top-level elements declared by the [declaration], along with their name tokens.
  ///
  static Iterable<(analyzer_element.Element, analyzer_token.Token)> _declaredTopLevelElements(
    analyzer_ast.CompilationUnitMember declaration,
  ) sync* {
    if (declaration is analyzer_ast.TopLevelVariableDeclaration) {
      for (final variable in declaration.variables.variables) {
        final element = _topLevelElement(variable.declaredFragment?.element);
        if (element != null) yield (element, variable.name);
      }
      return;
    }
    final element = _topLevelElement(declaration.declaredFragment?.element);
    if (element == null) return;
    final token = switch (declaration) {
      analyzer_ast.NamedCompilationUnitMember(:final name) => name,
      analyzer_ast.ExtensionDeclaration(:final name) => name,
      _ => null,
    };
    if (token != null) yield (element, token);
  }

  /// Applies the recorded edits to the [source] contents.
  ///
  static String _applyEdits(_MergedSource source) {
    final contents = source.result.content;
    final edits = [...source.edits]
      ..sort(
        (a, b) => a.offset != b.offset
            ? a.offset.compareTo(b.offset)
            : a.priority != b.priority
            ? a.priority.compareTo(b.priority)
            : a.end != b.end
            ? a.end.compareTo(b.end)
            : a.order.compareTo(b.order),
      );
    final buffer = StringBuffer();
    var position = 0;
    for (final edit in edits) {
      // Edits are applied in a single pass, in the order of their offsets, and must not overlap.
      if (edit.offset < position) {
        throw StateError('Overlapping merge edits in ${source.filePath} at offset ${edit.offset}.');
      }
      buffer
        ..write(contents.substring(position, edit.offset))
        ..write(edit.text);
      position = edit.end;
    }
    buffer.write(contents.substring(position));
    return buffer.toString().trim();
  }

  /// Converts a [dependency] declared by the [package] to a `pubspec.yaml` value.
  ///
  Object? _dependencyToYamlNode(
    SourcePackage package,
    pubspec_parse.Dependency dependency,
  ) {
    return switch (dependency) {
      pubspec_parse.HostedDependency(:final hosted, :final version) =>
        hosted?.url == null
            ? version.toString()
            : {
                'hosted': {
                  if (hosted!.declaredName != null) 'name': hosted.declaredName,
                  'url': hosted.url.toString(),
                },
                'version': version.toString(),
              },
      pubspec_parse.PathDependency(path: final dependencyPath) => {
        'path': _configuration.resolveDependencyPath(
          baseDirectory: package.sourceDirectory.path,
          dependencyPath: dependencyPath,
          preferCopies: false,
        ),
      },
      pubspec_parse.GitDependency(:final url, :final ref, path: final gitPath) => {
        'git': {
          'url': url.toString(),
          if (ref != null) 'ref': ref,
          if (gitPath != null) 'path': gitPath,
        },
      },
      pubspec_parse.SdkDependency(:final sdk, :final version) => {
        'sdk': sdk,
        if (version != pub_semver.VersionConstraint.any) 'version': version.toString(),
      },
    };
  }

  /// Returns the highest lower bound of the [constraints], or `null` if none of them has a lower bound.
  ///
  static pub_semver.Version? _highestLowerBound(Iterable<pub_semver.VersionConstraint?> constraints) {
    pub_semver.Version? minimum;
    for (final constraint in constraints) {
      if (constraint is pub_semver.VersionRange) {
        final min = constraint.min;
        if (min != null && (minimum == null || min > minimum)) minimum = min;
      }
    }
    return minimum;
  }

  /// Copies an asset (file or directory) declared by the [package] to the output directory.
  ///
  /// Returns `false` if the asset can't be included with the merged project.
  ///
  bool _copyAsset(SourcePackage package, String assetPath) {
    final sourcePath = path.join(package.sourceDirectory.path, assetPath);
    final outputPath = _configuration.outputDirectory.path;
    final destinationPath = path.normalize(path.join(outputPath, assetPath));
    if (!path.isWithin(outputPath, destinationPath)) {
      print('Warning: asset "$assetPath" of the ${package.name} package is placed outside of the package, it is not included.');
      return false;
    }
    final type = dart_io.FileSystemEntity.typeSync(sourcePath);
    if (type == dart_io.FileSystemEntityType.file) {
      dart_io.File(destinationPath).parent.createSync(recursive: true);
      dart_io.File(sourcePath).copySync(destinationPath);
    } else if (type == dart_io.FileSystemEntityType.directory) {
      for (final entity in dart_io.Directory(sourcePath).listSync(recursive: true)) {
        if (entity is! dart_io.File) continue;
        final target = path.join(destinationPath, path.relative(entity.path, from: sourcePath));
        dart_io.File(target).parent.createSync(recursive: true);
        entity.copySync(target);
      }
    } else {
      print('Warning: asset "$assetPath" of the ${package.name} package was not found, it is not included.');
      return false;
    }
    return true;
  }

  /// Merges the `flutter` sections of the source packages, copying the declared assets and fonts.
  ///
  Map<String, Object?>? _mergeFlutterConfiguration() {
    final merged = <String, Object?>{};
    final assets = <Object?>[];
    final fonts = <Object?>[];
    for (final package in _configuration.packages) {
      final configuration = package.pubspec.flutter;
      if (configuration == null) continue;
      if (configuration['uses-material-design'] == true) merged['uses-material-design'] = true;
      if (configuration['generate'] == true) {
        merged['generate'] = true;
        print('Warning: "flutter: generate: true" (e.g., localizations) is not supported by the merged project.');
      }
      final packageAssets = configuration['assets'];
      if (packageAssets is List) {
        for (final asset in packageAssets) {
          final assetPath = asset is Map ? asset['path'] : asset;
          if (assetPath is! String || !_copyAsset(package, assetPath)) continue;
          if (!assets.any((existing) => existing.toString() == asset.toString())) assets.add(asset);
        }
      }
      final packageFonts = configuration['fonts'];
      if (packageFonts is List) {
        for (final family in packageFonts) {
          final familyFonts = family is Map ? family['fonts'] : null;
          if (familyFonts is! List) continue;
          var included = true;
          for (final font in familyFonts) {
            final asset = font is Map ? font['asset'] : null;
            if (asset is! String || !_copyAsset(package, asset)) included = false;
          }
          if (included) fonts.add(family);
        }
      }
    }
    if (assets.isNotEmpty) merged['assets'] = assets;
    if (fonts.isNotEmpty) merged['fonts'] = fonts;
    return merged.isEmpty ? null : merged;
  }

  /// Generates a new `pubspec.yaml` file from the source package specifications.
  ///
  void _generateMergedPubspecFile() {
    final packages = _configuration.packages;
    final sourcePackageNames = _configuration.sourcePackages.toSet();
    Map<String, Object?> mergeDependencies(Map<String, pubspec_parse.Dependency> Function(pubspec_parse.Pubspec) section) {
      final result = <String, Object?>{};
      for (final package in packages) {
        for (final entry in section(package.pubspec).entries) {
          if (sourcePackageNames.contains(entry.key)) continue;
          final node = _dependencyToYamlNode(package, entry.value);
          final existing = result[entry.key];
          if (!result.containsKey(entry.key)) {
            result[entry.key] = node;
          } else if (dart_convert.jsonEncode(existing) != dart_convert.jsonEncode(node)) {
            // Hosted version constraints are intersected, other conflicting declarations are reported.
            final intersection = existing is String && node is String
                ? pub_semver.VersionConstraint.parse(existing).intersect(pub_semver.VersionConstraint.parse(node))
                : null;
            if (intersection != null && !intersection.isEmpty) {
              result[entry.key] = intersection.toString();
            } else {
              print(
                'Warning: conflicting declarations of the "${entry.key}" dependency (${dart_convert.jsonEncode(existing)} and '
                '${dart_convert.jsonEncode(node)}), the first one is used.',
              );
            }
          }
        }
      }
      return result;
    }

    final sdkMinimum = _highestLowerBound(packages.map((package) => package.pubspec.environment['sdk']));
    final environment = <String, Object?>{
      'sdk': sdkMinimum == null ? '^3.0.0' : '>=$sdkMinimum <${dart_math.max(4, sdkMinimum.major + 1)}.0.0',
    };
    final flutterMinimum = _highestLowerBound(packages.map((package) => package.pubspec.environment['flutter']));
    if (flutterMinimum != null) environment['flutter'] = '>=$flutterMinimum';
    final dependencies = mergeDependencies((pubspec) => pubspec.dependencies);
    final devDependencies = mergeDependencies((pubspec) => pubspec.devDependencies);
    final dependencyOverrides = mergeDependencies((pubspec) => pubspec.dependencyOverrides);
    final flutter = _mergeFlutterConfiguration();

    // A single package keeps its name, so that references to its own assets (e.g., `package: 'name'`) remain valid.
    final name = packages.length == 1 ? packages.single.name : 'merged_app';
    if (packages.length > 1 && flutter != null) {
      print(
        'Warning: the assets of the merged packages are included with the "$name" package, '
        'references to them with the original package names (e.g., `package: \'name\'`) must be updated.',
      );
    }
    final editor = yaml_edit.YamlEditor('');
    editor.update([], {
      'name': name,
      'description': 'A new merged application.',
      'version': '1.0.0+1',
      'publish_to': 'none',
      'environment': environment,
      if (dependencies.isNotEmpty) 'dependencies': dependencies,
      if (devDependencies.isNotEmpty) 'dev_dependencies': devDependencies,
      if (dependencyOverrides.isNotEmpty) 'dependency_overrides': dependencyOverrides,
      'flutter': ?flutter,
    });
    _configuration.mergedPubspecFile.writeAsStringSync('${editor.toString().trim()}\n');
  }

  /// Outputs all of the [Configuration.packages] `lib` contents to a single file.
  ///
  /// Returns `false` if the merged output could not be generated as valid Dart code.
  ///
  Future<bool> generateMergedProject() async {
    final collection = analyzer_context.AnalysisContextCollection(
      includedPaths: [for (final package in _configuration.packages) package.copyDirectory.path],
    );
    final sources = await _resolveSources(collection);
    final imports = <_MergedImport>[];
    final references = _prepareSources(sources, imports);
    final usedNames = {..._collector.usedIdentifiers};
    _resolvePrefixClashes(imports, usedNames);
    _resolvePrivateMemberClashes(sources, usedNames);
    final exportedNames = <String, analyzer_element.Element>{};
    final exports = _publicExports(sources, exportedNames);
    _resolveNameClashes(sources, references, imports, usedNames, exportedNames);
    _resolveExtensionClashes(sources, usedNames);
    await collection.dispose();

    final fileBuffer = StringBuffer();
    final importTexts = <String>{
      // An explicit import of `dart:core` (e.g., `import 'dart:core' as $core;` in generated code)
      // disables its implicit import, which the other merged libraries rely on.
      if (imports.any((import) => import.libraryKey == 'dart:core')) "import 'dart:core';",
      for (final import in imports) '${import.text};',
    };
    for (final directive in [...importTexts, ...exports]) {
      fileBuffer.writeln(directive);
    }
    fileBuffer.writeln();
    for (final source in sources) {
      final contents = _applyEdits(source);
      if (contents.isEmpty) continue;
      fileBuffer
        ..writeln(contents)
        ..writeln();
    }

    // Format available output data.
    var success = true;
    var formattedCode = fileBuffer.toString();
    try {
      formattedCode = _configuration.formatter.format(formattedCode);
    } catch (e) {
      success = false;
      print('Error: the merged code could not be formatted, as it is not valid Dart code:\n$e');
    }
    await _configuration.outputMergedFile.writeAsString(formattedCode);

    // Record the merged `pubspec.yaml` file and run package setup.
    _generateMergedPubspecFile();
    try {
      await Configuration.runPubGet(
        directory: _configuration.outputDirectory,
        flutter: _configuration.packages.any((package) => package.usesFlutter),
      );
    } on ConfigurationException catch (e) {
      print('Warning: dependencies of the merged project could not be resolved:\n$e');
    }
    return success;
  }
}

/// Collects the references to top-level declarations, and removes the first-party import prefixes.
///
class _MergeReferenceVisitor extends analyzer_visitor.RecursiveAstVisitor<void> {
  _MergeReferenceVisitor({
    required this.merger,
    required this.source,
    required this.references,
  });

  final ProjectMerger merger;

  final _MergedSource source;

  final List<_TopLevelReference> references;

  @override
  void visitImportDirective(analyzer_ast.ImportDirective node) {}

  @override
  void visitExportDirective(analyzer_ast.ExportDirective node) {}

  @override
  void visitPartDirective(analyzer_ast.PartDirective node) {}

  @override
  void visitPartOfDirective(analyzer_ast.PartOfDirective node) {}

  @override
  void visitLibraryDirective(analyzer_ast.LibraryDirective node) {}

  /// Records a reference to the [element] named by the [token], if it's a top-level declaration.
  ///
  void _record(analyzer_element.Element? element, analyzer_token.Token token, {required bool isPrefixed}) {
    final topLevelElement = ProjectMerger._topLevelElement(element);
    if (topLevelElement == null || token.lexeme != topLevelElement.name) return;
    // References through third-party import prefixes are not ambiguous.
    if (isPrefixed && !merger._isMergedLibrary(topLevelElement.library)) return;
    references.add(
      _TopLevelReference(
        source: source,
        offset: token.offset,
        end: token.end,
        element: topLevelElement,
      ),
    );
  }

  /// Records a kept import prefix, which may be renamed to avoid clashes between the merged files.
  ///
  void _recordPrefixUsage(analyzer_token.Token token) => merger._prefixUsages.add((source: source, token: token));

  /// Removes the [prefix] of a reference to a merged library, e.g., `helpers.` in `helpers.value`.
  ///
  /// Returns whether the prefix was removed.
  ///
  bool _removePrefix(analyzer_token.Token prefix, analyzer_token.Token period, analyzer_element.Element? element) {
    final library = element?.library;
    if (!merger._isMergedLibrary(library)) return false;
    source.addEdit(prefix.offset, period.end, '');
    return true;
  }

  @override
  void visitSimpleIdentifier(analyzer_ast.SimpleIdentifier node) {
    final element = node.element;
    if (element is analyzer_element.PrefixElement) {
      final parent = node.parent;
      if (parent is analyzer_ast.PrefixedIdentifier && parent.prefix == node) {
        if (!_removePrefix(node.token, parent.period, parent.identifier.element ?? ObjectCollector.assignedElement(parent.identifier))) {
          _recordPrefixUsage(node.token);
        }
      } else if (parent is analyzer_ast.MethodInvocation && parent.target == node) {
        if (parent.methodName.name == 'loadLibrary' && element.imports.every((import) => merger._isMergedLibrary(import.importedLibrary))) {
          // Deferred loading of a merged library, which is always loaded.
          source.addEdit(parent.offset, parent.end, 'Future<void>.value()');
        } else if (!_removePrefix(node.token, parent.operator!, parent.methodName.element)) {
          _recordPrefixUsage(node.token);
        }
      } else {
        _recordPrefixUsage(node.token);
      }
      return;
    }
    var resolved = element ?? ObjectCollector.assignedElement(node);
    if (resolved is analyzer_element.ConstructorElement) {
      resolved = node.name == resolved.enclosingElement.name ? resolved.enclosingElement : null;
    }
    final parent = node.parent;
    final isPrefixed = switch (parent) {
      analyzer_ast.PrefixedIdentifier(:final identifier, :final prefix) =>
        identifier == node && prefix.element is analyzer_element.PrefixElement,
      analyzer_ast.MethodInvocation(:final methodName, :final target) =>
        methodName == node && target is analyzer_ast.SimpleIdentifier && target.element is analyzer_element.PrefixElement,
      _ => false,
    };
    // Members accessed through a target (e.g., `object.member`) can't be top-level declarations.
    if (parent is analyzer_ast.PrefixedIdentifier && parent.identifier == node && !isPrefixed) return;
    if (parent is analyzer_ast.PropertyAccess && parent.propertyName == node) return;
    if (parent is analyzer_ast.MethodInvocation && parent.methodName == node && parent.target != null && !isPrefixed) return;
    _record(resolved, node.token, isPrefixed: isPrefixed);
  }

  @override
  void visitNamedType(analyzer_ast.NamedType node) {
    final importPrefix = node.importPrefix;
    var isPrefixed = importPrefix != null;
    if (importPrefix != null) {
      if (_removePrefix(importPrefix.name, importPrefix.period, node.element)) {
        isPrefixed = false;
      } else {
        _recordPrefixUsage(importPrefix.name);
      }
    }
    _record(node.element, node.name, isPrefixed: isPrefixed);
    super.visitNamedType(node);
  }
}

/// Renames the private class and extension members of the merged libraries, according to the [renames].
///
class _PrivateMemberVisitor extends analyzer_visitor.RecursiveAstVisitor<void> {
  _PrivateMemberVisitor({
    required this.source,
    required this.renames,
  });

  final _MergedSource source;

  /// New names, mapped by the private member keys.
  ///
  final Map<String, String> renames;

  void _rename(analyzer_element.Element? element, analyzer_token.Token token) {
    final newName = renames[ProjectMerger._privateMemberKey(element)];
    if (newName != null && token.lexeme.startsWith('_')) source.addEdit(token.offset, token.end, newName);
  }

  @override
  void visitImportDirective(analyzer_ast.ImportDirective node) {}

  @override
  void visitExportDirective(analyzer_ast.ExportDirective node) {}

  @override
  void visitMethodDeclaration(analyzer_ast.MethodDeclaration node) {
    _rename(node.declaredFragment?.element, node.name);
    super.visitMethodDeclaration(node);
  }

  @override
  void visitVariableDeclaration(analyzer_ast.VariableDeclaration node) {
    _rename(node.declaredFragment?.element, node.name);
    super.visitVariableDeclaration(node);
  }

  @override
  void visitRepresentationDeclaration(analyzer_ast.RepresentationDeclaration node) {
    _rename(node.fieldFragment?.element, node.fieldName);
    super.visitRepresentationDeclaration(node);
  }

  @override
  void visitFieldFormalParameter(analyzer_ast.FieldFormalParameter node) {
    _rename(node.declaredFragment?.element, node.name);
    super.visitFieldFormalParameter(node);
  }

  @override
  void visitSimpleIdentifier(analyzer_ast.SimpleIdentifier node) {
    _rename(node.element ?? ObjectCollector.assignedElement(node), node.token);
  }

  @override
  void visitPatternField(analyzer_ast.PatternField node) {
    final name = node.name;
    final newName = renames[ProjectMerger._privateMemberKey(node.element)];
    if (name != null && newName != null) {
      final nameToken = name.name;
      if (nameToken != null) {
        _rename(node.element, nameToken);
      } else {
        // Shorthand field (e.g., `Point(:var _x)`), the new name is inserted before the colon.
        source.addEdit(name.colon.offset, name.colon.offset, newName);
      }
    }
    super.visitPatternField(node);
  }
}

/// Rewrites the implicit extension member invocations to explicit extension overrides,
/// for the member names which become ambiguous once the libraries are merged.
///
class _ExtensionOverrideVisitor extends analyzer_visitor.RecursiveAstVisitor<void> {
  _ExtensionOverrideVisitor({
    required this.source,
    required this.memberNames,
    required this.overrideName,
  });

  final _MergedSource source;

  /// Names of the members of the extensions which become visible once merged.
  ///
  final Set<String> memberNames;

  /// Returns the name used to explicitly apply an extension, or `null` if it can't be referenced.
  ///
  final String? Function(analyzer_element.ExtensionElement extension) overrideName;

  /// Returns the extension declaring the instance member an [element] reference resolves to.
  ///
  static analyzer_element.ExtensionElement? _extensionOf(analyzer_element.Element? element) {
    final base = element?.baseElement;
    final enclosingElement = base?.enclosingElement;
    if (base is! analyzer_element.ExecutableElement || base.isStatic) return null;
    return enclosingElement is analyzer_element.ExtensionElement ? enclosingElement : null;
  }

  void _warn(analyzer_ast.AstNode node, String name) {
    final location = source.result.lineInfo.getLocation(node.offset);
    print(
      'Warning: ${source.filePath}:${location.lineNumber}: the "$name" extension member may resolve '
      'to a different extension in the merged file, and could not be made explicit.',
    );
  }

  /// Applies the extension declaring the [element] explicitly to the [target] of an invocation.
  ///
  void _override({
    required analyzer_ast.AstNode node,
    required analyzer_element.Element? element,
    required String name,
    required analyzer_ast.Expression? target,
    required bool isCascaded,
  }) {
    final extension = _extensionOf(element);
    if (extension == null || !memberNames.contains(name) || target is analyzer_ast.ExtensionOverride) return;
    // Members invoked on the implicit `this` are declared by the enclosing extension, resolved lexically.
    if (target == null && !isCascaded) return;
    final extensionName = overrideName(extension);
    if (isCascaded || target is analyzer_ast.SuperExpression || extensionName == null) {
      _warn(node, name);
      return;
    }
    source.addEdit(target!.offset, target.offset, '$extensionName(', priority: 0);
    source.addEdit(target.end, target.end, ')');
  }

  @override
  void visitImportDirective(analyzer_ast.ImportDirective node) {}

  @override
  void visitExportDirective(analyzer_ast.ExportDirective node) {}

  @override
  void visitMethodInvocation(analyzer_ast.MethodInvocation node) {
    _override(
      node: node,
      element: node.methodName.element,
      name: node.methodName.name,
      target: node.target,
      isCascaded: node.isCascaded,
    );
    super.visitMethodInvocation(node);
  }

  @override
  void visitPropertyAccess(analyzer_ast.PropertyAccess node) {
    _override(
      node: node,
      element: node.propertyName.element ?? ObjectCollector.assignedElement(node.propertyName),
      name: node.propertyName.name,
      target: node.target,
      isCascaded: node.isCascaded,
    );
    super.visitPropertyAccess(node);
  }

  @override
  void visitPrefixedIdentifier(analyzer_ast.PrefixedIdentifier node) {
    _override(
      node: node,
      element: node.identifier.element ?? ObjectCollector.assignedElement(node.identifier),
      name: node.identifier.name,
      target: node.prefix,
      isCascaded: false,
    );
    super.visitPrefixedIdentifier(node);
  }

  void _checkOperator(analyzer_ast.AstNode node, analyzer_element.Element? element) {
    final extension = _extensionOf(element);
    final name = element?.name;
    if (extension != null && name != null && memberNames.contains(name)) _warn(node, name);
  }

  @override
  void visitBinaryExpression(analyzer_ast.BinaryExpression node) {
    _checkOperator(node, node.element);
    super.visitBinaryExpression(node);
  }

  @override
  void visitIndexExpression(analyzer_ast.IndexExpression node) {
    _checkOperator(node, node.element);
    super.visitIndexExpression(node);
  }

  @override
  void visitPrefixExpression(analyzer_ast.PrefixExpression node) {
    _checkOperator(node, node.element);
    super.visitPrefixExpression(node);
  }

  @override
  void visitFunctionExpressionInvocation(analyzer_ast.FunctionExpressionInvocation node) {
    _checkOperator(node, node.element);
    super.visitFunctionExpressionInvocation(node);
  }
}
